export default{
    products: [
        {
            _id:'1',
            name:'Nike Runnig Shirt',
            category: 'Shirts',
            image: '/images/product-1.jpg',
            price: 60,
            brand: 'Nike',
            rating: '4.5',
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id:'2',
            name:'Adidas Casual Shirt',
            category: 'Shirts',
            image: '/images/product-2.jpg',
            price: 70,
            brand: 'Adidas',
            rating: '4.9',
            numReviews: 18,
            countInStock: 36,
        },
        {
            _id:'3',
            name:'Asics Runnig Pants 2',
            category: 'Pants',
            image: '/images/product-3.jpg',
            price: 90,
            brand: 'Asics',
            rating: '4.0',
            numReviews: 40,
            countInStock: 56,
        },
        {
            _id:'4',
            name:'Adidas Originals Coat ',
            category: 'Jackets',
            image: '/images/product-4.jpg',
            price: 190,
            brand: 'Adidas',
            rating: '4.9',
            numReviews: 120,
            countInStock: 86,
        },
        {
            _id:'5',
            name:'Puma Men Jacket',
            category: 'Jackets',
            image: '/images/product-5.jpg',
            price: 150,
            brand: 'Puma',
            rating: '4.1',
            numReviews: 30,
            countInStock: 20,
        },
        {
            _id:'6',
            name:'Nike Dry-fit Pants',
            category: 'Pants',
            image: '/images/product-6.jpg',
            price: 99,
            brand: 'Nike',
            rating: '4.5',
            numReviews: 18,
            countInStock: 6,
        },

    ],
};